# Generated by Django 5.0.6 on 2026-04-22 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64, unique=True, verbose_name='ID чата')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('username', models.CharField(blank=True, max_length=128, null=True, verbose_name='Username')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(verbose_name='ID сообщения')),
                ('hashtag', models.CharField(db_index=True, max_length=128, verbose_name='Хэштег')),
                ('text', models.TextField(blank=True, verbose_name='Текст поста')),
                ('author_name', models.CharField(blank=True, max_length=255, verbose_name='Имя автора')),
                ('author_username', models.CharField(blank=True, max_length=128, verbose_name='Username автора')),
                ('author_id', models.CharField(blank=True, max_length=64, verbose_name='ID автора')),
                ('posted_at', models.DateTimeField(db_index=True, verbose_name='Время публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Записан в БД')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='dashboard.trackedchat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-posted_at'],
                'unique_together': {('message_id', 'chat')},
            },
        ),
    ]
